#!/bin/sh

if [ "$#" -gt 0 ]; then
    if [ "$1" = "php-fpm" ]; then
        while true; do
            php-fpm7.4 -F

            if ! php-fpm7.4 -t; then
                echo 'php-fpm config test failed, restarting in 30s...'
                sleep 30
            fi
        done
    else
        echo "unknown command: $1"
    fi
    exit
fi

grep_release() {
    grep -oP --color=never '\d{4}-\d{2}-\d{2}'
}

INSTALLED_VERSION="$(< /app/VERSION grep_release)"
NEW_VERSION="$(echo -n "$DOKUWIKI_RELEASE" | grep_release)"

if [ "$INSTALLED_VERSION" != "$NEW_VERSION" ]; then
    echo Install / update dokuwiki to ${DOKUWIKI_RELEASE}...
    tar -C "/app" --strip-components=1 -zxf /dokuwiki.tar.gz
    (cd /app \
        && grep -Ev '^($|#)' data/deleted.files | xargs -n 1 rm -vf
    )
fi

echo 'Fix any permission issues...'
chown -R www-data "/app"    

INSTALL_LOCK=/app/.dokuwiki.installed
if [ -f "/app/install.php" ]; then
    if [ -f "$INSTALL_LOCK" ]; then
        echo Remove install.php...
        rm -f /app/install.php
    else
        echo 'Next boot will remove "install.php"'
        touch "$INSTALL_LOCK"
    fi
fi

# custom init.
if [ -d /init.d ]; then
    source /init.d/*.sh
fi

mkdir -p /run/php
"$0" php-fpm &

echo 'Starting nginx...'
nginx -g 'daemon off;'
echo 'nginx shutdown.'
