name: "Dokuwiki"

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "dokuwiki/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dokuwiki_release:
          - stable_2020-07-29
          - stable_2018-04-22c

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/jixunmoe/dokuwiki
          labels: |
            org.opencontainers.image.description=For spin up a new dokuwiki instance.
          tags: |
            type=raw,value=${{ matrix.dokuwiki_release }}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: dokuwiki
          build-args:
            - DOKUWIKI_RELEASE="${{ matrix.dokuwiki_release }}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline
