name: "Dokuwiki"

on:
  push:
    branches:
      - main
    paths:
      - "dokuwiki/**"
      - ".github/workflows/dokuwiki.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dokuwiki_release:
          - stable_2022-07-31a
          - stable_2020-07-29a

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Multi-arch build
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/jixunmoe/dokuwiki
          labels: |
            org.opencontainers.image.description=For spin up a new dokuwiki instance.
          tags: |
            type=raw,value=${{ matrix.dokuwiki_release }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: dokuwiki
          platforms: |
            linux/arm64
            linux/amd64
          build-args: |
            DOKUWIKI_RELEASE=${{ matrix.dokuwiki_release }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline
