name: "Hugo"

on:
  push:
    branches:
      - main
    paths:
      - "hugo/**"
      - ".github/workflows/hugo.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        VER:
          - 0.101.0
          - 0.91.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/jixunmoe/hugo
          labels: |
            org.opencontainers.image.description=Hugo (extended) environment based on debian
          tags: |
            type=raw,value=${{ matrix.VER }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: hugo
          build-args: |
            VER=${{ matrix.VER }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline
